CREATE TABLE CLIENTES(
CODIGO INTEGER PRIMARY KEY,
DATA_CAD TIMESTAMP,
DATA_ALT TIMESTAMP,
USER_CAD VARCHAR(40),
USER_ALT VARCHAR(40),
CLIENTE  VARCHAR(50) NOT NULL,
APELIDO  VARCHAR(30),
CEP VARCHAR(8),
LOGRADOURO VARCHAR(50),
NUMERO INTEGER,
BAIRRO VARCHAR(50),
COD_CIDADE INTEGER NOT NULL,
TELEFONE VARCHAR(12),
EMAIL VARCHAR(40),
CPF VARCHAR(11) NOT NULL UNIQUE,
RG VARCHAR(14),
SEXO INTEGER,
DATA_NASC TIMESTAMP,
TIPO_PESSOA SMALLINT NOT NULL,
FOREIGN KEY (COD_CIDADE) REFERENCES CIDADES(CODIGO)
);

alter table clientes
add cod_condPag integer;

alter table clientes
add foreign key (cod_condpag) references cond_pag(codigo);