CREATE TABLE PRODUTOS(
	CODIGO INTEGER PRIMARY KEY,
	DATA_CAD TIMESTAMP,
	DATA_ALT TIMESTAMP,
	USER_CAD VARCHAR(40),
	USER_ALT VARCHAR(40),
	PRODUTO VARCHAR(50) NOT NULL,
	OBS VARCHAR(100),
	ESTOQUE INTEGER,
	PRECO_CUSTO NUMERIC(12,2),
	PRECO_VENDA NUMERIC(12,2),
	IMAGEM BLOB,
	COD_FORNECEDOR INTEGER,
	COD_UNIDADE INTEGER,
	COD_SUBGRUPO INTEGER,
	FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDORES(CODIGO),
	FOREIGN KEY (COD_UNIDADE) REFERENCES UNIDADES(CODIGO),
	FOREIGN KEY (COD_SUBGRUPO) REFERENCES SUBGRUPOS(CODIGO)
);